import { MenuItem } from './types'

// Images from Unsplash (stable CDN, crop to card size)
// FoodImage component will show emoji fallback if any URL fails to load
const U = (id: string) =>
  `https://images.unsplash.com/${id}?w=600&h=420&fit=crop&auto=format&q=80`

export const menu: MenuItem[] = [
  {
    id: '1',
    name: 'Cơm Rang Trứng',
    description: 'Cơm rang thơm với trứng gà tươi đánh bông, hành lá xanh, cà rốt băm — món kinh điển không thể thiếu',
    price: 35000,
    image: U('photo-1512058564366-18510be2db19'),
    emoji: '🍳',
    category: 'classic',
    tag: 'bestseller',
    rating: 4.9,
    soldCount: 1240,
    prepTime: 10,
  },
  {
    id: '2',
    name: 'Cơm Rang Thịt Bò',
    description: 'Thịt bò Mỹ thái mỏng xào tái với cơm rang vàng, tiêu đen Phú Quốc, hành tây, ớt chuông ba màu',
    price: 55000,
    image: U('photo-1544025162-d76694265947'),
    emoji: '🥩',
    category: 'classic',
    tag: 'hot',
    rating: 4.8,
    soldCount: 870,
    prepTime: 12,
  },
  {
    id: '3',
    name: 'Cơm Rang Hải Sản',
    description: 'Tôm sú, mực ống, cua biển xào với cơm rang kiểu Thái, rau thì là thơm, nước mắm nhĩ Phú Quốc',
    price: 65000,
    image: U('photo-1565299624946-b28f40a0ae38'),
    emoji: '🦑',
    category: 'seafood',
    tag: 'new',
    rating: 4.7,
    soldCount: 620,
    prepTime: 15,
  },
  {
    id: '4',
    name: 'Cơm Rang Gà Gừng',
    description: 'Ức gà xé nhỏ ướp gừng tươi, xào cùng cơm rang vàng ươm, hành phi giòn rụm, tiêu sọ',
    price: 45000,
    image: U('photo-1604908176997-125f25cc6f3d'),
    emoji: '🍗',
    category: 'classic',
    rating: 4.7,
    soldCount: 750,
    prepTime: 12,
  },
  {
    id: '5',
    name: 'Cơm Rang Dương Châu',
    description: 'Công thức Trung Hoa cổ điển: tôm, xá xíu, lap xưởng, trứng, đậu Hà Lan, nấm hương, cải thảo',
    price: 50000,
    image: U('photo-1603133872878-684f208fb84b'),
    emoji: '🥡',
    category: 'classic',
    tag: 'bestseller',
    rating: 4.9,
    soldCount: 1050,
    prepTime: 13,
  },
  {
    id: '6',
    name: 'Cơm Rang Tôm Bơ Tỏi',
    description: 'Tôm sú size lớn rang với bơ Anchor, tỏi vàng giòn, tiêu xanh Campuchia, rau mùi tươi',
    price: 60000,
    image: U('photo-1555951015-6da893cef4a9'),
    emoji: '🍤',
    category: 'seafood',
    rating: 4.8,
    soldCount: 540,
    prepTime: 13,
  },
  {
    id: '7',
    name: 'Cơm Rang Thập Cẩm',
    description: 'Hỗn hợp thịt heo, gà, xúc xích, trứng chiên, nấm đông cô, cà rốt, đậu que — đủ vị, đủ no',
    price: 55000,
    image: U('photo-1569050467447-ce54b3bbc37d'),
    emoji: '🥘',
    category: 'classic',
    tag: 'bestseller',
    rating: 4.8,
    soldCount: 930,
    prepTime: 15,
  },
  {
    id: '8',
    name: 'Cơm Rang Kim Chi',
    description: 'Kim chi cải thảo lên men truyền thống Korea, thịt ba chỉ giòn, trứng ốp la, tương gochujang',
    price: 55000,
    image: U('photo-1534482421-64566f976cfa'),
    emoji: '🌶️',
    category: 'fusion',
    tag: 'hot',
    rating: 4.6,
    soldCount: 480,
    prepTime: 13,
  },
  {
    id: '9',
    name: 'Cơm Rang Cua Biển',
    description: 'Thịt cua biển tươi ngọt lừng, trứng cua vàng ươm, hành lá, gừng, rưới dầu hào Maggi',
    price: 80000,
    image: U('photo-1414235077428-338989a2e8c0'),
    emoji: '🦀',
    category: 'seafood',
    tag: 'new',
    rating: 4.9,
    soldCount: 310,
    prepTime: 18,
  },
  {
    id: '10',
    name: 'Cơm Rang Phô Mai Bacon',
    description: 'Fusion sáng tạo: bacon Mỹ giòn rụm, phô mai Mozzarella tan chảy, trứng ốp lòng đào, sốt mayo',
    price: 60000,
    image: U('photo-1568901346375-23c9450c58cd'),
    emoji: '🧀',
    category: 'fusion',
    tag: 'new',
    rating: 4.7,
    soldCount: 420,
    prepTime: 15,
  },
]

export const categories = [
  { key: 'all',        label: 'Tất cả',     emoji: '🍽️' },
  { key: 'bestseller', label: 'Bán chạy',   emoji: '⭐' },
  { key: 'classic',    label: 'Classic',    emoji: '🍳' },
  { key: 'seafood',    label: 'Hải sản',    emoji: '🦐' },
  { key: 'fusion',     label: 'Fusion',     emoji: '✨' },
] as const
